"""Auto-generation of unit/integration tests for a ported target (Phase 8).

Turns the LiteSpec verification pipeline into a self-contained pytest module: for
every ported function it emits a ``verify_function`` test (structural + concrete +
differential, whichever applies), plus a coverage test that asserts there are no
``mismatch``-classified functions and that every function is covered.
"""

from __future__ import annotations


def generate_tests(
    source_path: str,
    function_names: list[str],
    *,
    type_model_name: str = "liteos",
    config_expr: str = "Config.liteos_default()",
    module_name: str = "test_generated_liteos",
) -> str:
    """Return the text of an auto-generated pytest module for the given functions."""
    fns = "\n".join(f"    {name!r}," for name in function_names)
    return f'''"""Auto-generated verification tests for target functions.

Generated by ``litespec generate-tests``: each ported function is verified through
the layered equivalence chain (structural + concrete + differential), and a coverage
test asserts that no function is classified as a verification mismatch.
"""

from pathlib import Path

import pytest

from litespec.equivalence import verify_function
from litespec.equivalence.coverage import coverage_report
from litespec.extraction.config import Config
from litespec.type_mapping import load_type_model

_SRC_PATH = Path({source_path!r})
SRC = _SRC_PATH.read_bytes() if _SRC_PATH.exists() else None
_TM = load_type_model({type_model_name!r})
_CFG = {config_expr}

_FUNCTIONS = [
{fns}
]


@pytest.mark.skipif(SRC is None, reason=f"source not present: {{_SRC_PATH}}")
@pytest.mark.parametrize("name", _FUNCTIONS)
def test_each_function_is_verified(name):
    result, chain = verify_function(SRC, name, type_model=_TM, config=_CFG)
    assert result.status == "pass", f"{{name}}: errors={{result.errors}} warnings={{result.warnings}}"
    assert len(chain.links) == 5


@pytest.mark.skipif(SRC is None, reason=f"source not present: {{_SRC_PATH}}")
def test_coverage_has_no_mismatches():
    counts, per_fn = coverage_report(SRC, _FUNCTIONS, type_model=_TM, config=_CFG)
    assert counts.get("mismatch", 0) == 0, per_fn
    assert sum(counts.values()) == len(_FUNCTIONS), counts
'''
