"""Appendix X failure-mode catalogue.

The ``FailureMode`` enum enumerates every normative failure-mode identifier
declared across Volume 1 (Rules 0.1–9.22, 14.1–14.4, and the Phase 1 scope) and
Volume 2 Appendix X (negative-test catalogue). Values equal their names, so
``FailureMode["abi_entry_unbound"].value == "abi_entry_unbound"``.
"""

from __future__ import annotations

import enum
from typing import Final

_FAILURE_MODE_NAMES: Final[tuple[str, ...]] = (
    "abi_entry_unbound",
    "adapter_missing_undisclosed",
    "aspirational_gap_undisclosed",
    "aspirational_rule_in_certified_claim",
    "binder_type_annotation_missing",
    "break_continue_undeclared",
    "config_expr_arithmetic_class_missing",
    "config_expr_decision_undeclared",
    "config_expr_nonlinear_unacknowledged",
    "config_expr_nonlinear_undecided",
    "config_preset_cycle",
    "config_preset_unresolved",
    "control_flow_ambient_loop_id",
    "control_flow_fallthrough_missing",
    "control_flow_token_incomplete",
    "control_flow_token_undeclared",
    "correctness_kind_mismatch",
    "correctness_kind_propagation_violation",
    "d67_fragment_schema_violation",
    "d67_head_role_mismatch",
    "d67_head_rule_mismatch",
    "d67_index_out_of_bounds",
    "d67_invocation_missing",
    "d67_normal_post_misaligned",
    "d67_path_condition_wrong_segment",
    "dag_serialization_invalid",
    "dag_serialization_undeclared",
    "decrease_mode_vocabulary_mismatch",
    "dependency_scan_unrecorded",
    "derived_fragment_type_leak",
    "descent_factor_missing",
    "desugaring_helper_arity_ambiguity",
    "diagram_shorthand_label",
    "duplicate_rule_definition",
    "exit_condition_local_pre_missing",
    "exit_disjunct_post_missing",
    "exit_label_string_form",
    "exit_post_implication_failure",
    "exit_post_projection_violation",
    "exit_state_model_registration_order_violation",
    "exit_state_model_unpopulated",
    "exit_state_target_unbound",
    "exit_state_undeclared",
    "expression_type_ambiguous",
    "fallthrough_predicate_source_violation",
    "for_c_init_lost",
    "for_c_stage2_undeclared",
    "for_c_substitution_capture",
    "fragment_complexity_unrecorded",
    "frame_condition_violated",
    "gluing_seed_unpromoted",
    "grammar_import_undeclared",
    "grammar_nonterminal_undefined",
    "guard_complexity_unrecorded",
    "hardware_encoding_field_missing",
    "hash_binding_field_mismatch",
    "hash_binding_index_out_of_bounds",
    "hash_binding_undeclared",
    "helper_arity_mismatch",
    "helper_definition_missing",
    "helper_signature_mismatch",
    "hoare_decomposition_not_recursive",
    "hoare_if_positional_lookup",
    "hoare_reconstruction_failed",
    "hoare_subpart_rule_ref_invalid",
    "indicator_naming_noncanonical",
    "inner_loops_unresolved",
    "interface_check_id_duplicate",
    "interface_check_id_missing",
    "interface_relation_kind_invalid",
    "interface_relation_kind_missing",
    "label_construction_violation",
    "labeled_break_misrouted",
    "lir_contract_predicate_type_mismatch",
    "lir_node_id_unstable",
    "lir_spec_field_access_violation",
    "lir_spec_loop_analysis_missing",
    "llm_artifact_unvalidated",
    "llm_provenance_missing",
    "loop_construct_undeclared",
    "loop_optimization_certificates_erased",
    "loop_optimization_certificates_orphaned",
    "loop_optimization_kind_type_mismatch",
    "loop_optimization_schema_mismatch",
    "lowering_or_verification_field_missing",
    "manifest_duplicate_field",
    "mk_sub_callee_missing",
    "mk_sub_iface_type_mismatch",
    "non_ascii_body",
    "parent_exit_label_double_prefix",
    "path_condition_eager_conjunction",
    "path_dag_adapter_version_missing",
    "path_dag_hash_mismatch",
    "path_dag_op_missing",
    "path_dag_ref_missing",
    "path_ref_unresolved",
    "phase2_migration_incomplete",
    "phase_2_dependency_undisclosed",
    "phase_scope_violation",
    "pipeline_fold_state_erasure",
    "placeholder_in_normative_text",
    "predicate_ref_unresolved",
    "predicate_shorthand_rejected",
    "profile_bounding_metadata_missing",
    "profile_gate_unacknowledged",
    "promotion_obligation_routing_invalid",
    "promotion_record_invalid",
    "promotion_threshold_unrecorded",
    "qualify_names_exit_label_collision",
    "resolve_target_ambiguous",
    "return_position_unsupported",
    "rule_body_missing",
    "rule_classification_mismatch",
    "rule_classification_missing",
    "rule_range_citation",
    "schema_type_undefined",
    "seq_exit_state_incomplete",
    "seq_normal_post_violation",
    "shared_post_recursion_failure",
    "source_function_selector_ambiguous",
    "spec_record_field_access_violation",
    "spec_record_lookup_incomplete",
    "spec_record_ref_version_dangling",
    "stated_theorem_used",
    "structural_dispatch_by_name_convention",
    "stutter_encoding_schema_violation",
    "stutter_encoding_undeclared",
    "sub_part_kind_ambiguous",
    "sub_part_kind_undeclared",
    "syscall_mapping_field_missing",
    "type_identifier_unresolved",
    "typing_context_leaked_to_ir",
    "untyped_substitution_in_typed_context",
    "variant_both_mode_stuttering_forbidden",
    "variant_not_bounded_below",
    "variant_progress_decrease_failed",
    "variant_synthesis_mode_mismatch",
    "variant_well_foundedness_unproved",
    "while_body_partition_violation",
)

FailureMode = enum.Enum("FailureMode", {name: name for name in _FAILURE_MODE_NAMES})  # type: ignore[misc]


def failure_mode(name: str) -> FailureMode:
    """Resolve a failure-mode identifier to its enum member (raises ValueError if unknown)."""
    return FailureMode[name]


def all_failure_modes() -> tuple[FailureMode, ...]:
    """Return every failure mode in declaration order."""
    return tuple(FailureMode)
