"""Unsafe-core Rust emission (Phase 4)."""

from __future__ import annotations

from litespec.lir.effect_expr_ast import EffectExpr
from litespec.lowering.effect_expr_to_rust import (
    addr_taken_vars,
    allocate_addr_slots,
    assigned_targets,
    memory_model,
    render_effect_rust,
    sanitize_ident,
    set_addr_taken,
    set_field_offsets,
    set_variadic,
)
from litespec.lowering.goto_elimination import eliminate_gotos
from litespec.lowering.rust_type_mapping import int_type, rust_default, rust_type
from litespec.lowering.stub_scaffold import collect_external_symbols, render_stub_scaffold


def emit_function(
    name: str,
    params: list[tuple[str, str]],
    return_type: str,
    state_vars: list[tuple[str, str]],
    effect: EffectExpr,
    *,
    unsafe: bool = True,
) -> str:
    """Emit a single Rust function from a LIR effect.

    Locals are pre-declared at the top of the body so that assignments inside
    nested blocks (``if``/``while``/``do``) reassign rather than shadow them.
    """
    effect = eliminate_gotos(effect)
    types = {n: t for n, t in state_vars}
    types.update({n: t for n, t in params})
    declared = {n for n, _ in params} | {n for n, _ in state_vars}
    reassigned = assigned_targets(effect)
    # Address-taken locals (``&x``) live in the flat memory model, not the Rust stack.
    addr_taken = addr_taken_vars(effect) & declared
    set_addr_taken(allocate_addr_slots(sorted(addr_taken)))
    body = render_effect_rust(effect, types, declared=declared)
    param_str = ", ".join(f"{'mut ' if n in reassigned else ''}{sanitize_ident(n)}: {rust_type(t)}" for n, t in params)
    rt = rust_type(return_type)
    unsafe_kw = "unsafe " if unsafe else ""

    lines = [f"pub {unsafe_kw}fn {name}({param_str}) -> {rt} {{"]
    for n, t in state_vars:
        if n in addr_taken:
            continue  # the local lives in MEM; its slot is pre-zeroed
        lines.append(f"    let mut {sanitize_ident(n)}: {rust_type(t)} = {rust_default(t)};")
    for bline in body.splitlines():
        lines.append(f"    {bline}" if bline else "")
    lines.append("}")
    return "\n".join(lines)


def emit_module(
    name: str,
    params: list[tuple[str, str]],
    return_type: str,
    state_vars: list[tuple[str, str]],
    effect: EffectExpr,
    *,
    structs: str = "",
    unsafe: bool = True,
) -> str:
    """Emit a self-contained Rust module (prelude + structs + stubs + function)."""
    effect = eliminate_gotos(effect)
    unknown_types, functions, constants, _fn_ptrs = collect_external_symbols(effect, params, state_vars, return_type)
    set_variadic({n for n, (_, _, v) in functions.items() if v})
    set_field_offsets({})
    scaffold = render_stub_scaffold(unknown_types, functions, constants)
    parts = [
        "// generated by litespec (Phase 4 lowering)",
        "#![allow(dead_code)]",
        "#![allow(unused_assignments)]",
        "#![allow(unused_variables)]",
        "#![allow(unused_mut)]",
        "#![allow(unused_parens)]",
        "#![allow(non_snake_case)]",
        "#![allow(clippy::all)]",
        "#![allow(arithmetic_overflow)]",  # C unsigned arithmetic wraps
    ]
    it = int_type()
    parts.append("// flat word-addressable memory model\n" + memory_model(it))
    if structs:
        parts.append(structs.rstrip())
    if scaffold:
        parts.append("// stubs for external symbols (macros, helpers, typedefs, constants)")
        parts.append(scaffold)
    parts.append(emit_function(name, params, return_type, state_vars, effect, unsafe=unsafe))
    return "\n\n".join(parts) + "\n"
