"""Generate the OpenHarmony ``BUILD.gn`` for a target's ported Rust crate.

The generator is config-driven: it reads ``TargetRequirements`` (``port_name``,
``asm_files``, ``target_triple``, ``linker_script``, ``qemu_cpu``) and emits a
``static_library`` target that links the arch ``.S`` files with the Rust static
library produced by the target's ``run.sh build`` entry point.
"""

from __future__ import annotations

from litespec.targets.loader import TargetRequirements


def generate_build_gn(target: TargetRequirements) -> str:
    """Emit a config-driven ``BUILD.gn`` for the target's ported crate."""
    port = target.port_name or target.name
    triple = target.target_triple
    linker = target.linker_script
    mcpu = target.mcpu
    asm_sources = "\n".join(f'    "{f}",' for f in target.asm_files)
    rust_lib = f"targets/{port}/lib{port}.a"
    cflags = f'  cflags = [ "-mcpu={mcpu}" ]\n' if mcpu else ""
    return (
        f"# generated by litespec — OpenHarmony build integration for {port}\n"
        f"# target: {target.name} (target_triple: {triple})\n"
        f"# linker_script: {linker}\n"
        f"\n"
        f'import("//build/lite/config/component/lite_component.gni")\n'
        f"\n"
        f"# The ported Rust crate is compiled to a static library by the target's\n"
        f"# entry point (`targets/{port}/run.sh build`), then linked with the arch .S.\n"
        f'static_library("{port}") {{\n'
        f"  sources = [\n"
        f"{asm_sources}\n"
        f'    "{rust_lib}",\n'
        f"  ]\n"
        f"{cflags}"
        f"}}\n"
    )
